name: Checkmarx Security Scan
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - master
  workflow_dispatch:
 
permissions:
  contents: read
 
jobs:
  checkmarx-ast:
    permissions:
      contents: read # Required for actions/checkout to fetch code
      security-events: write # Needed for GitHub/codeql-action/upload-sarif
      actions: read # Only required for private repositories
 
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      # Step 2: Run Checkmarx AST Scan
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.3.33
        with:
        # Provide the AST portal URL
         base_uri: https://eu.ast.checkmarx.net
        # Provide the Tenant for AST portal URL
         cx_tenant: ast_abdul_ansari
       # Client ID for AST portal authentication
         cx_client_id: ${{ secrets.CX_CLIENT_ID }}
       # Secret key for AST portal authentication
         cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
    # Select a Checkmarx Project Name
         project_name: ${{ github.repository }}
    # Branch name
         branch:  ${{ github.head_ref || github.ref }}
         scan_params: 
           --report-format pdf ; 
           --output-name Mckinsey_Demo.pdf ; 
           --report-pdf-email harsh.gokani@checkmarx.com

  # dast:
  #   runs-on: ubuntu-latest
  #   name: Checkmarx DAST Scan 
  #   steps:
  #     - name: Create and permission output folder
  #       run: |
  #         mkdir -p ${{ runner.temp }}/output
  #         sudo chmod 777 ${{ runner.temp }}/output

  #     - name: Run DAST-CLI command
  #       run: |
  #         docker run --pull=always \
  #           -v ${{ runner.temp }}/output:/output \
  #           -e CX_APIKEY=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5ZDMzNDA4Yy0yMGVjLTQ2ZjgtYWY5ZC1kZTljYmU0MWZlOTIifQ.eyJpYXQiOjE3NzUyMTM5NTEsImp0aSI6IjU5MWMzMzI4LWJhMDktNDM4Zi1iNTVjLTQ1MjI3MzcyMzhjNCIsImlzcyI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvYXN0X2FiZHVsX2Fuc2FyaSIsImF1ZCI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvYXN0X2FiZHVsX2Fuc2FyaSIsInN1YiI6ImMwY2M2NDBhLTMwNDQtNDM3YS05NzI4LTZhZGVlMjA4YjFmNSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJhc3QtYXBwIiwic2lkIjoiOGZmMzcwMjAtYzlkZS00MGJiLWE2ODctNjdiZmUzNjk4YWMyIiwic2NvcGUiOiJyb2xlcyBwcm9maWxlIGVtYWlsIGlhbS1hcGkgYXN0LWFwaSBvZmZsaW5lX2FjY2VzcyJ9.vMa8CFFD2ByJUHXoyV-9TCOsSAlcYDw9zXL1iGt1jcdvdwCjkd0r48ZNN8Cw9bHXWyg7PdVDBaWLUkK-TdWgIg \
  #           checkmarx/dast:latest \
  #           scan \
  #           --environment-id=d93345be-fc7d-4096-9d76-e99a0292ffed \
  #           --base-url=https://eu.ast.checkmarx.net \
  #           --output=/output
           
  #     - name: Set permission on output folder
  #       run: |
  #        sudo chown -R 1001:1001 ${{ runner.temp }}/output
  #     - name: Upload ZAP output
  #       uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
  #       if: always()
  #       with:
  #         name: zap-output
  #         path: ${{ runner.temp }}/output
